### ISSUE TITLE
Need a dependency

### ISSUE THREAD

**Issue by danieltigse** [Criptext/dockerfiles#7]
When I update to node 4.x I got the following error:

```
> canvas@1.4.0 install /app/web-server/node_modules/canvas
> node-gyp rebuild

make: Entering directory `/dist/web-server/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.h:22:0,
                 from ../src/Canvas.cc:7:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from ../src/Canvas.h:11:0,
                 from ../src/Canvas.cc:7:

```

The solution was install C++ compiler. 

We need to include this lines to the docker file and test:
https://gist.github.com/omnus/6404505

**Comment by danieltigse** [comment]
I also had this issue:

```
Error: Cannot find module '../build/Release/canvas'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/app/web-server/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

and I run this line:

```
node-gyp rebuild
```

inside node_modules/canvas

**Comment by luisloaiza** [comment]
ok we are adding this new lines in the lines 

```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update -y
sudo apt-get install -y g++-4.8
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
```

**Comment by erikaperugachi** [comment]
The temporal fix is add this line MANUALLY:

```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update -y
sudo apt-get install -y g++-4.8
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
```
